### ISSUE TITLE
Trojan Detected by Antivirus

### ISSUE THREAD

**Issue by aarifpanjwani** [psidex/EACS#3]
Windows Defender Antivirus detects Trojan:Win32/Azden.B!cl and quarantines executable file

**Comment by psidex** [comment]
Not sure why this would happen, but it is a false positive.

I you are having trouble using the exe I have compiled you can try building it yourself, just clone the repo, install the requirements and run the `build.bat` file

(sorry for the super late reply!)

**Comment by aarifpanjwani** [comment]
Thank you for your reply.

I thought it it must have been a false positive.  Windows Defender automatically quarantines exe file upon unzipping.  However, after setting an exception rule was able to install without issue.

Thanks

________________________________
