### ISSUE TITLE
Disable all other configs when clicking one config

### ISSUE THREAD

**Issue by EgonVLC** [psidex/EACS#7]
I've been using EqualizeAPO for several years, just discovered your utility and it's almost perfect for me. I have diferent profiles for each headphone/speakers on my setup (3 of them) and change them depending on which I'm using. I't would be perfect to have an option so loading a config unload all other configs, so it's a single click. Now I have to load next and unload previous. 

Thanks in advance.

**Comment by psidex** [comment]
Hi, sorry about the late reply, I somehow completely missed this.

Thanks for letting me know, this sounds like a great idea!

I'll start working on it soon 👍

**Comment by EgonVLC** [comment]
Woha! Thank you! It will be the best companion to EqualizerAPO!

**Comment by psidex** [comment]
I've just released [v0.4.0](https://github.com/psidex/EACS/releases/tag/v0.4.0), this now has the feature you were asking for 🎉

Let me know if you think of any other features you think might be useful!

edit: Just updated to [v0.4.1](https://github.com/psidex/EACS/releases/tag/v0.4.1)

**Comment by EgonVLC** [comment]
Just tested it, It's perfect! Thank you very much!!
